### ISSUE TITLE
Did you test the GPU speed measures end-to-end time per image?

### ISSUE THREAD

**Issue by mheriyanto** [yasenh/libtorch-yolov5#10]
I tested your code to detect object on a video using GPU. I used GTX 1050 Ti LP and I got **3 FPS**. What is it corresponding with your test result?
Thanks @yasenh

**Comment by yasenh** [comment]
Hi @mheriyanto, you could refer to this issue #3, and I tested it with a GeForce GTX 1070 GPU.
So you can use `$ nvidia-smi -l` to make sure your GPU is utilized during the inference, 3 FPS sounds little bit slower than I expected even on a 1050 Ti GPU.

**Comment by mheriyanto** [comment]
Okay, Thanks @yasenh, I will close this issue and then refer to issue #3.
