### ISSUE TITLE
No obj problem

### ISSUE THREAD

**Issue by name333** [yasenh/libtorch-yolov5#11]
hello ,
    Let me post a question in your project. In detect.cpp,
// if none remain then process next image
        if (det.size(1) == 0) {
            continue;
        }
det.size(1) == 0　should be　det.size(0) == 0　Is that right？

**Comment by yasenh** [comment]
Hi @name333, thanks for pointing that out and it was fixed in my previous commits: cc7887c
You could pull from the latest master.
