### ISSUE TITLE
The models pt to TorchScript what it's unsuccessful

### ISSUE THREAD

**Issue by molyswu** [yasenh/libtorch-yolov5#14]
Hi
python models/export.py --weights yolov5s.pt --img 640 --batch 1

Fusing layers...
Model Summary: 120 layers, 7.06617e+06 parameters, 7.06617e+06 gradients
Traceback (most recent call last):
File "models/export.py", line 41, in
y = model(img) # dry run

.
.
.

type(self).name, name))
torch.nn.modules.module.ModuleAttributeError: 'Detect' object has no attribute 'm'

**Comment by yasenh** [comment]
Hi @molyswu, could to you try to pull the latest updates and re-download the pre-trained model from the yolov5 repo? And make sure your torch version meet the requirement, e.g. v1.6.0 now
