### ISSUE TITLE
why GPU run time longger than CPU run time？？

### ISSUE THREAD

**Issue by 158545614** [yasenh/libtorch-yolov5#15]
![image](https://user-images.githubusercontent.com/65331444/93192600-6c19fc80-f778-11ea-8640-f2ff45e81994.png)
![image](https://user-images.githubusercontent.com/65331444/93193092-fe220500-f778-11ea-8795-47789c9dc6d5.png)

**Comment by yasenh** [comment]
Hi @158545614 , please check out https://github.com/yasenh/libtorch-yolov5#faq, you can test with multiple images in a loop or test with a video with little bit modification
