### ISSUE TITLE
Memory leak issues, the program will die

### ISSUE THREAD

**Issue by molyswu** [yasenh/libtorch-yolov5#18]
Hi
Memory leak issues, 3 consecutive for ./libtorch-yolov5 --source ../images/bus.jpg --weights ../weights/yolov5s.torchscript.pt --gpu --view-img

If the memory is not released, the program will die.

Thanks

**Comment by yasenh** [comment]
@molyswu  Could elaborate how to replicate the issue? It may related the parser library I added recently
