### ISSUE TITLE
Does anyone run GPU inference successfully?

### ISSUE THREAD

**Issue by Jelly123456** [yasenh/libtorch-yolov5#19]
I could not run the inference with GPU enabled. I follow the instructions to modify the export.py code to export the torchscript model with GPU, but when inferring with libtorch, it cannot load the weight.

Does anyone know how to solve it?

My OS is windows 10 and it is able to run the CPU torchscript model.

Thanks in advance.

**Comment by yasenh** [comment]
Hi @Jelly123456 , what is the error message? I tested few days ago (in Ubuntu) and it works fine. What is your pytorch version and did you pull the latest yolov5 python version?

**Comment by Jelly123456** [comment]
@yasenh Thanks very much for your reply.
There is no error message. This is the output when running with GPU:

![image](https://user-images.githubusercontent.com/29449336/95406281-99f3fa80-094c-11eb-8227-4f253973bb79.png)



pytorch version is V1.6 and I am using the latest yolov5 version.

**Comment by yasenh** [comment]
@Jelly123456 I tested locally without any issue, it seems crashed during "module_.forward(inputs)", not sure if it is related to Windows.. Maybe you can follow [PyTorch official example](https://pytorch.org/tutorials/advanced/cpp_export.html) and make sure it works on you GPU

**Comment by yasenh** [comment]
Feel free to share your experience

**Comment by Jelly123456** [comment]
@yasenh Thanks very much for your testing.

I did some internet search and found that this could be the bug for libtorch in Windows.
https://github.com/pytorch/pytorch/issues/23217
https://github.com/yf225/pytorch-cpp-issue-tracker/issues/378
