### ISSUE TITLE
Suggestions on creation MSVS project builds

### ISSUE THREAD

**Issue by rtrahms** [yasenh/libtorch-yolov5#20]
Beyond cmake builds, do you have any suggestions on how to build code like this for Visual Studio?
Thanks in advance...

**Comment by yasenh** [comment]
@rtrahms maybe you can take a look at [CMake projects in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=vs-2019)
