### ISSUE TITLE
isTuple() INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by wolfworld6** [yasenh/libtorch-yolov5#21]
when i run the code,i got this error ,how could i solve it?

terminate called after throwing an instance of 'c10::Error'
  what():  isTuple() INTERNAL ASSERT FAILED at "/dxd/libtorch-yolov5/libtorch/include/ATen/core/ivalue_inl.h":842, please report a bug to PyTorch. Expected Tuple but got GenericList
Exception raised from toTuple at /dxd/libtorch-yolov5/libtorch/include/ATen/core/ivalue_inl.h:842 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7f569de58eb9 in /dxd/libtorch-yolov5/libtorch/lib/libc10.so)
frame #1: c10::IValue::toTuple() const & + 0xe5 (0x4206cd in ./libtorch-yolov5)
frame #2: ./libtorch-yolov5() [0x41916a]
frame #3: ./libtorch-yolov5() [0x4316f6]
frame #4: __libc_start_main + 0xf0 (0x7f5654d44840 in /lib/x86_64-linux-gnu/libc.so.6)
frame #5: ./libtorch-yolov5() [0x4176b9]

Aborted (core dumped)

**Comment by yasenh** [comment]
https://github.com/yasenh/libtorch-yolov5#faq
@wolfworld6 if you use cpu version, please make sure you don't pass --gpu flag

**Comment by wolfworld6** [comment]
> https://github.com/yasenh/libtorch-yolov5#faq
> @wolfworld6 if you use cpu version, please make sure you don't pass --gpu flag

i have done this ,as follow:
model = attempt_load(opt.weights, map_location=torch.device('cuda'))
model.model[-1].export = False
gs = int(max(model.stride))  # grid size (max stride)
opt.img_size = [check_img_size(x, gs) for x in opt.img_size]  # verify img_size are gs-multiples
img = torch.zeros((opt.batch_size, 3, *opt.img_size)).to(device='cuda')

**Comment by wolfworld6** [comment]
> https://github.com/yasenh/libtorch-yolov5#faq
> @wolfworld6 if you use cpu version, please make sure you don't pass --gpu flag

that is my fault,i do that twice,thx v much!

**Comment by yasenh** [comment]
No problem, good to hear that you fixed it!
