### ISSUE TITLE
Performance difference between running model in python vs c++?

### ISSUE THREAD

**Issue by govindamagrawal** [yasenh/libtorch-yolov5#24]
Hi @yasenh ,
The code is beautifully written in c++. Even I tried but could not perform the end to end successfully due to lack of expertise in c++ in libtorch. Could you also provide some sort of statistics that could tell whether running the model in c++ improves the performance as compared to running the same model in python in GPU? 

What I guess is there should not be much difference, even if it exists. And if exists, why such performance difference is coming? I know I am asking too much, but if you could analyze it, it would be really useful.

**Comment by yasenh** [comment]
Hi @govindamagrawal, there are some benchmark under "issue https://github.com/yasenh/libtorch-yolov5/issues/3". 
For the more detailed analysis, I may still need little bit time to get more familiar with libtorch and pytorch (e.g. asynchronous execution), I will post the updates once I get better understanding :)
