### ISSUE TITLE
torch::Tensor preds = module.forward({ imgTensor }).toTuple()->elements()[0].toTensor()

### ISSUE THREAD

**Issue by rrjia** [yasenh/libtorch-yolov5#27]
torch::Tensor preds = module.forward({ imgTensor }).toTuple()->elements()[0].toTensor()
code error, because torch forward get a GenericList not a Tuple

**Comment by yasenh** [comment]
@rrjia checkout: https://github.com/yasenh/libtorch-yolov5#faq

**Comment by rrjia** [comment]
thank you very much ,i found it
"Make sure "model.model[-1].export = False" when running export script"

**Comment by yasenh** [comment]
Yep, give a try and most likely it will solve the issue
