### ISSUE TITLE
how use this code for CPU-Only?

### ISSUE THREAD

**Issue by Yasin40** [yasenh/libtorch-yolov5#30]
Hi, I wanna use this code to inference with cpu-only, without cuda support?

**Comment by yasenh** [comment]
@Yasin40 The answer is Yes, you can take a look at the README

**Comment by Yasin40** [comment]
> @Yasin40 The answer is Yes, you can take a look at the README

I got error when make it without cuda (on system without cuda installed)

**Comment by Wangbenzhi** [comment]
i think  remove  "#include <c10/cuda/CUDAStream.h> and include <ATen/cuda/CUDAEvent.h>" in detector.h would work

**Comment by yasenh** [comment]
@Wangbenzhi  thanks for pointing it out, agreed

**Comment by SHK2018** [comment]
Kind of curious about the first two frame interpret time issue ON GPU. The first frame which is an empty image will take 200-300 ms and the second one which is my incoming image will take  more than 1 s(forget the exact number but much slower than the first frame). And the following image will just consume 10 ms per frame. Wonder what reason for the time issue of the second image which consume much more time than the rest of frame? Thanks for you help!
