### ISSUE TITLE
I did all the steps but in the make step I get this error

### ISSUE THREAD

**Issue by alikarimi120** [yasenh/libtorch-yolov5#34]
[ 33%] Building CXX object CMakeFiles/libtorch-yolov5.dir/src/detector.cpp.o
In file included from /home/alikarimi/libtorch-yolov5/libtorch/include/c10/util/ArrayRef.h:19:0,
                 from /home/alikarimi/libtorch-yolov5/libtorch/include/c10/core/MemoryFormat.h:5,
                 from /home/alikarimi/libtorch-yolov5/libtorch/include/ATen/core/TensorBody.h:5,
                 from /home/alikarimi/libtorch-yolov5/libtorch/include/ATen/Tensor.h:3,
                 from /home/alikarimi/libtorch-yolov5/libtorch/include/ATen/Context.h:4,
                 from /home/alikarimi/libtorch-yolov5/libtorch/include/ATen/ATen.h:5,
                 from /home/alikarimi/libtorch-yolov5/libtorch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/alikarimi/libtorch-yolov5/libtorch/include/torch/script.h:3,
                 from /home/alikarimi/libtorch-yolov5/include/detector.h:5,
                 from /home/alikarimi/libtorch-yolov5/src/detector.cpp:1:
/home/alikarimi/libtorch-yolov5/libtorch/include/c10/util/C++17.h:24:2: error: #error You need C++14 to compile PyTorch
 #error You need C++14 to compile PyTorch
  ^~~~~
In file included from /home/alikarimi/libtorch-yolov5/libtorch/include/c10/util/Exception.h:5:0,
                 from /home/alikarimi/libtorch-yolov5/libtorch/include/c10/core/Device.h:5,
                 from /home/alikarimi/libtorch-yolov5/libtorch/include/c10/core/Allocator.h:6,
                 from /home/alikarimi/libtorch-yolov5/libtorch/include/ATen/ATen.h:3,
                 from /home/alikarimi/libtorch-yolov5/libtorch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/alikarimi/libtorch-yolov5/libtorch/include/torch/script.h:3,
                 from /home/alikarimi/libtorch-yolov5/include/detector.h:5,
                 from /home/alikarimi/libtorch-yolov5/src/detector.cpp:1:
/home/alikarimi/libtorch-yolov5/libtorch/include/c10/util/StringUtil.h:86:17: error: expected primary-expression before ‘auto’
 inline decltype(auto) str(const Args&... args) {
                 ^~~~
/home/alikarimi/libtorch-yolov5/libtorch/include/c10/util/StringUtil.h:86:17: error: expected ‘)’ before ‘auto’
/home/alikarimi/libtorch-yolov5/libtorch/include/c10/util/StringUtil.h:86:17: error: expected primary-expression before ‘auto’
/home/alikarimi/libtorch-yolov5/libtorch/include/c10/util/StringUtil.h:86:17: error: expected primary-expression before ‘auto’
/home/alikarimi/libtorch-yolov5/libtorch/include/c10/util/StringUtil.h:86:17: error: expected primary-expression before ‘auto’
/home/alikarimi/libtorch-yolov5/libtorch/include/c10/util/StringUtil.h:86:17: error: expected primary-expression before ‘auto’
/home/alikarimi/libtorch-yolov5/libtorch/include/c10/util/StringUtil.h:86:8: error: expected unqualified-id before ‘decltype’
 inline decltype(auto) str(const Args&... args) {
        ^~~~~~~~
In file included from /home/alikarimi/libtorch-yolov5/libtorch/include/c10/core/Device.h:5:0,
                 from /home/alikarimi/libtorch-yolov5/libtorch/include/c10/core/Allocator.h:6,
                 from /home/alikarimi/libtorch-yolov5/libtorch/include/ATen/ATen.h:3,
                 from /home/alikarimi/libtorch-yolov5/libtorch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/alikarimi/libtorch-yolov5/libtorch/include/torch/script.h:3,
                 from /home/alikarimi/libtorch-yolov5/include/detector.h:5,
                 from /home/alikarimi/libtorch-yolov5/src/detector.cpp:1:
/home/alikarimi/libtorch-yolov5/libtorch/include/c10/core/Device.h: In member function ‘void c10::Device::validate()’:
/home/alikarimi/libtorch-yolov5/libtorch/include/c10/core/Device.h:96:5: error: ‘str’ is not a member of ‘c10’
     TORCH_CHECK(index_ == -1 || index_ >= 0,
     ^
/home/alikarimi/libtorch-yolov5/libtorch/include/c10/core/Device.h:98:5: error: ‘str’ is not a member of ‘c10’
     TORCH_CHECK(!is_cpu() || index_ <= 0,
     ^
/home/alikarimi/libtorch-yolov5/libtorch/include/c10/core/Allocator.h: In member function ‘void* c10::Allocator::raw_allocate(size_t)’:
/home/alikarimi/libtorch-yolov5/libtorch/include/c10/core/Allocator.h:163:5: error: ‘str’ is not a member of ‘c10’
     AT_ASSERT(dptr.get() == dptr.get_context());
     ^
/home/alikarimi/libtorch-yolov5/libtorch/include/c10/core/Allocator.h:163:5: error: ‘str’ is not a member of ‘c10’
     AT_ASSERT(dptr.get() == dptr.get_context());
     ^
.....

**Comment by alikarimi120** [comment]
my gcc :
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by alikarimi120** [comment]
Solved!

**Comment by alikarimi120** [comment]
change in cmake:
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

**Comment by yasenh** [comment]
thanks @alikarimi120 , updated in 2ff39dc
