### ISSUE TITLE
terminated call error when run /libtorch-yolov5

### ISSUE THREAD

**Issue by alikarimi120** [yasenh/libtorch-yolov5#35]
![Capture](https://user-images.githubusercontent.com/30392099/103891396-01157c80-50ff-11eb-909c-f24c097c0feb.JPG)

**Comment by alikarimi120** [comment]
i sure  "model.model[-1].export = False" in export.py

**Comment by alikarimi120** [comment]
Can you help? @yasenh 
Which yolov5 release did you use? https://github.com/ultralytics/yolov5/releases

**Comment by yasenh** [comment]
I tested it on v3.0 and v3.1 @alikarimi120 , are you using v4.0? And which version of libtorch are you using?

**Comment by alikarimi120** [comment]
libortch :
https://download.pytorch.org/libtorch/cu102/libtorch-cxx11-abi-shared-with-deps-1.6.0.zip

i tested it on v2.0 , v3.1 and v4 but I get this error (picture above)

**Comment by alikarimi120** [comment]
Can you send me a yolov5s.torchscript.pt? of course, I think the problem is with the pytorch version, not the model conversion؟
@yasenh

**Comment by alikarimi120** [comment]
> I tested it on v3.0 and v3.1 @alikarimi120 , are you using v4.0? And which version of libtorch are you using?

libortch :
https://download.pytorch.org/libtorch/cu102/libtorch-cxx11-abi-shared-with-deps-1.6.0.zip

i tested it on v2.0 , v3.1 and v4 but I get this error (picture above)

**Comment by alikarimi120** [comment]
Can you send me a yolov5s.torchscript.pt? of course, I think the problem is with the pytorch version, not the model conversion?
@yasenh

**Comment by alikarimi120** [comment]
I've tried nigthly version of libtorch and error dissapear
command:
wget https://download.pytorch.org/libtorch/nightly/cu101/libtorch-cxx11-abi-shared-with-deps-latest.zip

look it :
https://github.com/pytorch/pytorch/issues/17054

**Comment by yasenh** [comment]
libtorch >= 1.6.0 should work
