### ISSUE TITLE
Export ONNX with CUDA

### ISSUE THREAD

**Issue by CharlieYe12** [yasenh/libtorch-yolov5#36]
Hi！
I have modified  the "export.py to support GPU，but still receive the following error:

> RuntimeError: Input, output and indices must be on the current device

Do you have any suggestions on how this issue can be resolved?
Thanks!

**Comment by zhiqwang** [comment]
Ah-ha, @AlaylmYC , I think it is not necessary to export to a `onnx` model in this repo.

If you export to a `torchscript` model on **CPU**, processing like the following can solve the problem of device inconsistency. In other words, `libtorch` can handle the problem of device switching.

```cpu
device_type = torch::kCUDA;
module = torch::jit::load(weights);
module.to(device_type);
```

**Comment by yasenh** [comment]
@AlaylmYC did you resolve the issue?
