### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by Jelly123456** [yasenh/libtorch-yolov5#43]
Hi, thanks for much for creating this repo and it is really awesome.

My question is how to debug with libtorch? Now I face the problem of "segmentation fault(core dumped)" after running the warm-up.

![image](https://user-images.githubusercontent.com/29449336/110913261-dee2e980-834f-11eb-8c75-ac3564dd0142.png)

I tried to debug with VSCode, but I could not go deep into libtorch library.

[OS]: SUSE
[Libtorch]: Nightly

Is it compulsory to use debug version of libtorch?

**Comment by zhiqwang** [comment]
Hi @Jelly123456 

LibTorch is a subset of Python, if you only have some bugs in LibTorch backend, I think that one option is through the Python environment. Check [here](https://pytorch.org/docs/stable/jit.html#disable-jit-for-debugging) for more details.

> If there is hard-to-debug error in one of your TorchScript models, you can use this flag to force everything to run using native Python. Since TorchScript (scripting and tracing) is disabled with this flag, you can use tools like `pdb` to debug the model code.
