### ISSUE TITLE
 auto detections = output.toTuple()->elements()[0].toTensor();

### ISSUE THREAD

**Issue by lulersoft** [yasenh/libtorch-yolov5#5]
执行到  auto detections = output.toTuple()->elements()[0].toTensor(); 出现错误中断：

inline c10::intrusive_ptr<ivalue::Tuple> IValue::toTuple() const & {
  AT_ASSERT(isTuple(), "Expected Tuple but got ", tagKind());
  return toIntrusivePtr<ivalue::Tuple>();
}

**Comment by yasenh** [comment]
@lulersoft please refer to issue #4 , make sure you set "model.model[-1].export = False" when export the model

**Comment by lulersoft** [comment]
谢谢，已经成功运行，非常棒。

**Comment by huhuhu12138** [comment]
> 谢谢，已经成功运行，非常棒。

你好，请教一下

**Comment by huhuhu12138** [comment]
我设置为false 导出会失败，请问您这边是如何解决的

**Comment by MHGL** [comment]
首先非常感谢ultralytics大神，我们团队把yolov5模型重构了，并且复现了和原仓库同样的水平，优势是可以端到端转换移动端模型，如果你有时间有需要，请移步[yolov5](https://github.com/DeepVAC/yolov5)，期待各位的驾临。
