### ISSUE TITLE
from where i got yolov5s.torchscript.pt file?

### ISSUE THREAD

**Issue by RizwanMunawar** [yasenh/libtorch-yolov5#52]
I Successfully compiled project, but unable to find **yolov5s.torchscript.pt** file, and in **yolov5/export.py** line 29 is quite different as you mentioned? How can i get yolov5s.torchscript file?

**Comment by gauravlochab** [comment]
python export.py --weights yolov5s.pt --img 640 --batch 1 in yoloV5 repo
