### ISSUE TITLE
The model I want to export runs on multiple GPUs

### ISSUE THREAD

**Issue by zhongqingyang** [yasenh/libtorch-yolov5#55]
I use 
```
# line 28
img = torch.zeros((opt.batch_size, 3, *opt.img_size)).to(device='cuda')  
# line 31
model = attempt_load(opt.weights, map_location=torch.device('cuda'))
```

But it can only be loaded on GPU0。
```
# line 28
img = torch.zeros((opt.batch_size, 3, *opt.img_size)).to(device='cuda:1')  
# line 31
model = attempt_load(opt.weights, map_location=torch.device('cuda:1'))
```
But it can only be loaded on GPU1.

Can you give an opinion.

**Comment by nobody-cheng** [comment]
> I use
> 
> ```
> # line 28
> img = torch.zeros((opt.batch_size, 3, *opt.img_size)).to(device='cuda')  
> # line 31
> model = attempt_load(opt.weights, map_location=torch.device('cuda'))
> ```
> 
> But it can only be loaded on GPU0。
> 
> ```
> # line 28
> img = torch.zeros((opt.batch_size, 3, *opt.img_size)).to(device='cuda:1')  
> # line 31
> model = attempt_load(opt.weights, map_location=torch.device('cuda:1'))
> ```
> 
> But it can only be loaded on GPU1.
> 
> Can you give an opinion.

are you fix??

**Comment by zhongqingyang** [comment]
No, I'm thinking about giving up yolov5




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月8日(星期三) 晚上9:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yasenh/libtorch-yolov5] The model I want to export runs on multiple GPUs (#55)





  
我使用
 # line 28 img = torch.zeros((opt.batch_size, 3, *opt.img_size)).to(device='cuda')   # line 31 model = attempt_load(opt.weights, map_location=torch.device('cuda'))  
但它只能加载到GPU0上。
 # line 28 img = torch.zeros((opt.batch_size, 3, *opt.img_size)).to(device='cuda:1')   # line 31 model = attempt_load(opt.weights, map_location=torch.device('cuda:1'))  
但它只能加载到GPU1上。
 
你能给出一个意见吗？
  
你修复了吗？？
 
—
您收到此邮件是因为您创作了该线程。
直接回复此电子邮件，在 GitHub 上查看，或取消订阅。
使用适用于iOS或Android的 GitHub Mobile 随时随地对通知进行分类。
