### ISSUE TITLE
当检测一张没有任何可识别内容的图片，引发错误崩溃。

### ISSUE THREAD

**Issue by lulersoft** [yasenh/libtorch-yolov5#6]
0x00007FFB68A2A799 处(位于 Demo.exe 中)有未经处理的异常: Microsoft C++ 异常: c10::Error，位于内存位置 0x00000012BCF9BE60 处。

代码中断跳转到 ：kernel_lambda.h
    auto operator()(Parameters... args) -> decltype(std::declval<FuncType>()(std::forward<Parameters>(args)...)) {
      return kernel_func_(std::forward<Parameters>(args)...);
    }

调试在这里开始引起崩溃停止：
        // get the max classes score at each result (e.g. elements 5-84)
        std::tuple<torch::Tensor, torch::Tensor> max_classes = torch::max(det.slice(1, item_attr_size, item_attr_size + num_classes), 1);

**Comment by yasenh** [comment]
Thanks for the feedback, fixed in commit cc7887ce024a5f7b64ae4fa381589bf86e56abdb

**Comment by lulersoft** [comment]
更新后，已经完美解决，谢谢。
