### ISSUE TITLE
libtorch-yolov7 can be used for this project?

### ISSUE THREAD

**Issue by futureflsl** [yasenh/libtorch-yolov5#64]
I want to use yolov7 for libtorch,but I can't code...

**Comment by Ellohiye** [comment]
> I want to use yolov7 for libtorch,but I can't code...

你好，请问您后续有做这个方面的实验吗？这个项目可以用于yolov7吗

**Comment by tronghieuit** [comment]
@futureflsl you can see yolov7 libtorch here: https://github.com/tronghieuit/Libtorch-CUDA-YoloV7
