### ISSUE TITLE
getting warning and just yolov5s.torchscript.pt file when export model

### ISSUE THREAD

**Issue by mheriyanto** [yasenh/libtorch-yolov5#7]
I installed Python>=3.8 and PyTorch>=1.6 and also ONNX>=1.7.
I used [export.py](https://github.com/yasenh/libtorch-yolov5/blob/master/utils/export.py) with your suggestion here: https://github.com/yasenh/libtorch-yolov5#torchscript-model-export 

and I got these results, just got **yolov5s.torchscript.pt**, I didn't get **yolov5s.onnx**:

![image](https://user-images.githubusercontent.com/22278148/89380175-49c8a400-d721-11ea-8a25-8ef983913110.png)

When I use weight (yolov5s.torchscript.pt) to run inference, I got these:

![image](https://user-images.githubusercontent.com/22278148/89380633-0884c400-d722-11ea-8fdd-d8a111fcafe0.png)

Is there any advice? Thank you.

**Comment by yasenh** [comment]
Hi @mheriyanto, so my env is PyTorch 1.5.1, and I can export the model  with onnx 1.7.0 (but I didn't test it with onnxruntime).
Anyway for this project, you only need the TorchScript version of model, could you give a try with PyTorch 1.5.1? And meanwhile I can test with PyTorch 1.6.0 as well.

**Comment by mheriyanto** [comment]
Hello @yasenh , I exported the TorchScript version of model using PyTorch 1.6.0 but model can't be used like [before](https://github.com/yasenh/libtorch-yolov5/issues/7#issue-673298785). So yesterday, I exported the TorchScript version of model using torch 1.5.1, torchvision 0.6.1 and onnx 1.7.0, I got **yolov5s.torchscript.pt** and **yolov5s.onnx** but there is warning about CoreML like this:

![image](https://user-images.githubusercontent.com/22278148/89633735-7cfc6600-d8ce-11ea-94d4-af4846c6cfcb.png)

When I use weight (yolov5s.torchscript.pt) to run inference, I got these (on CPU):

![image](https://user-images.githubusercontent.com/22278148/89634195-2f342d80-d8cf-11ea-81b9-76903924daee.png)

on GPU:

![image](https://user-images.githubusercontent.com/22278148/89634363-715d6f00-d8cf-11ea-9437-1c8c5b0c28fb.png)

**Comment by yasenh** [comment]
@mheriyanto whats your libtorch version?

**Comment by mheriyanto** [comment]
@yasenh LibTorch 1.4.0, OpenCV 4.2.0, CUDA 10.1, and Ubuntu 18.04.

**Comment by yasenh** [comment]
@mheriyanto  Could you try LibTorch 1.5.1?
wget https://download.pytorch.org/libtorch/cu101/libtorch-cxx11-abi-shared-with-deps-1.5.1%2Bcu101.zip

**Comment by mheriyanto** [comment]
@yasenh I tried LibTorch 1.5.1 with CUDA 10.1 and it worked for me. Thank you.

![image](https://user-images.githubusercontent.com/22278148/89700862-19207e80-d95c-11ea-82fc-56c00adc75a8.png)
