### ISSUE TITLE
如何能使用 224X的图

### ISSUE THREAD

**Issue by lulersoft** [yasenh/libtorch-yolov5#8]
尝试修改 std::vector<float> pad_info = LetterboxImage(img_input, img_input, cv::Size(640, 640)); 为std::vector<float> pad_info = LetterboxImage(img_input, img_input, cv::Size(224, 224)); 出现问题。

**Comment by yasenh** [comment]
Hi @lulersoft, for smaller image you can still use 640 as padding size, this is what original yolov5 implemented:
https://github.com/ultralytics/yolov5/blob/master/utils/datasets.py#L137, and theoretically you should able to change padding size as well, I will check it out later on. Thanks for your feedback.
