### ISSUE TITLE
如果使用低版本的opencv可以？？？

### ISSUE THREAD

**Issue by dreamhighchina** [yasenh/libtorch-yolov5#9]

**Comment by yasenh** [comment]
@dreamhighchina  Should be fine, maybe some parameters need to be change accordingly

**Comment by dreamhighchina** [comment]
大佬，你有转好的模型？？？我用官网的转模型脚本，会出现CoreML export failure: module 'coremltools' has no attribute 'convert'的错误，然后目录下面有两个文件，yolov5s.onnx和yolov5s.torchscript.pt，yolov5s.torchscript.pt放到你的工程里面会报这个错误，Error loading the model!

**Comment by yasenh** [comment]
Please refer to issue #7 and make sure you have correct lib versions (e.g. libtorch 1.5.1). I will try latest libtorch version later on.
